services:
  selenium-chrome:
    container_name: selenium-chrome
    image: seleniarm/standalone-chromium
    platform: linux/arm64
    ports:
      - "4444:4444"
    networks:
      - selenium-net
    environment:
      - SE_NODE_SESSION_TIMEOUT=60 # Set session timeout to 120 seconds
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2G

  script:
    container_name: script
    depends_on:
      - selenium-chrome
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      OUTPUT_PATH: /app/downloads
    working_dir: /app
    volumes:
      - .:/app
    networks:
      - selenium-net

networks:
  selenium-net:
    driver: bridge
