services:
  selenium-chrome:
    container_name: selenium-chrome
    image: seleniarm/standalone-chromium
    platform: linux/arm64
    ports:
      - "4444:4444"
    networks:
      - selenium-net
    environment:
      - SE_NODE_SESSION_TIMEOUT=600
      - SE_NODE_MAX_SESSIONS=8
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_SCREEN_WIDTH=1280
      - SE_SCREEN_HEIGHT=720
      - SE_SCREEN_DEPTH=24
    deploy:
      resources:
        limits:
          cpus: "6"
          memory: 16G
        reservations:
          cpus: "4"
          memory: 8G
    shm_size: "512m"

  script:
    container_name: script
    depends_on:
      - selenium-chrome
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      OUTPUT_PATH: /app/downloads
    working_dir: /app
    volumes:
      - .:/app
    networks:
      - selenium-net

networks:
  selenium-net:
    driver: bridge
